dist: trusty
language: java
jdk: oraclejdk8

addons:
  artifacts: true

branches:
  only:
    - master
    - /^build\/.*$/

cache:
  directories:
    - $HOME/.lein
    - $HOME/.local
    - $HOME/.m2

before_install:
  - unset _JAVA_OPTIONS  # Avoid unwanted _JAVA_OPTIONS set by Travis CI
  - echo "Sudo-enabled build? ${TRAVIS_SUDO}"

install:
  - ./waiter/bin/ci/install-lein

matrix:
  include:
    - name: 'Waiter unit tests'
      before_script: cd waiter
      script: ./bin/ci/run-unit-tests.sh
